version: '3'

services:
  engine:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/engine:${DOCKER_IMAGE_TAG}
    build: ../images/engine
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/engine:/usr/src/app
    links:
      - clickhouse:clickhouse
    depends_on:
      - kafka

  fetcher.ping:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/fetcher.ping:${DOCKER_IMAGE_TAG}
    build: ../images/fetchers/fetcher.ping
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.ping:/usr/src/app
    depends_on:
      - kafka

  fetcher.lync:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/fetcher.lync:${DOCKER_IMAGE_TAG}
    build: ../images/fetchers/fetcher.lync
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.lync:/usr/src/app
    depends_on:
      - kafka

  fetcher.active_directory:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/fetcher.active_directory:${DOCKER_IMAGE_TAG}
    build: ../images/fetchers/fetcher.active_directory
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.active_directory:/usr/src/app
    depends_on:
      - kafka

  fetcher.exchange:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/fetcher.exchange:${DOCKER_IMAGE_TAG}
    build: ../images/fetchers/fetcher.exchange
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.exchange:/usr/src/app
    depends_on:
      - kafka

  fetcher.vk:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/fetcher.vk:${DOCKER_IMAGE_TAG}
    build: ../images/fetchers/fetcher.vk
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.vk:/usr/src/app
      - ../../data/screenshots:/data/screenshots
    depends_on:
      - kafka

  fetcher.ok:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/fetcher.ok:${DOCKER_IMAGE_TAG}
    build: ../images/fetchers/fetcher.ok
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.ok:/usr/src/app
      - ../../data/screenshots:/data/screenshots
    depends_on:
      - kafka

  fetcher.fb:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/fetcher.fb:${DOCKER_IMAGE_TAG}
    build: ../images/fetchers/fetcher.fb
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.fb:/usr/src/app
      - ../../data/screenshots:/data/screenshots
    depends_on:
      - kafka

  fetcher.instagram:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/fetcher.instagram:${DOCKER_IMAGE_TAG}
    build: ../images/fetchers/fetcher.instagram
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.instagram:/usr/src/app
      - ../../data/screenshots:/data/screenshots
    depends_on:
      - kafka

  smtp:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/smtp:${DOCKER_IMAGE_TAG}
    build: ../images/smtp
    environment:
      BROKER_URL: "kafka://kafka:9092"
      SMTP_SERVER: smtp.mail.ru
      SMTP_USERNAME: SmartHR@inbox.ru
      SMTP_PASSWORD: greenatomhackathon
    volumes:
      - ../images/smtp:/usr/src/app
    depends_on:
      - kafka

  www:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/www:${DOCKER_IMAGE_TAG}
    build: ../images/www
    environment:
      DATA_DIR: /data/playbooks/demo
      IMAGE_DIR: /data/images
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/www:/usr/src/app
      - ../../data/playbooks:/data/playbooks
      - ../../data/images:/data/images
    ports:
      - 80:8501
    depends_on:
      - kafka

  predictor:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/predictor:${DOCKER_IMAGE_TAG}
    build: ../images/predictor
    environment:
      DATA_DIR: /data/playbooks
    volumes:
      - ../images/predictor:/usr/src/app
      - ../../data/playbooks/train:/data/playbooks

  simulator:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/simulator:${DOCKER_IMAGE_TAG}
    build: ../images/simulator
    volumes:
      - ../images/simulator:/usr/src/app
