version: '3'

services:
  base:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/base:${DOCKER_IMAGE_TAG}
    build: ../images/bases/base

  chrome-selenium:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/base-chrome-selenium:${DOCKER_IMAGE_TAG}
    build: ../images/bases/chrome-selenium
