version: '3'

services:
  data:
    image: citylix-greenatom-ml/data:develop
    build: ../images/data
    environment:
      DATA_DIR: /data/playbooks/demo
    volumes:
      - ../../data/playbooks:/data/playbooks
