version: '3'

services:
  data:
    image: ${DOCKER_IMAGE_REGISTRY}/citylix-greenatom-ml/data:${DOCKER_IMAGE_TAG}
    build: ../images/data
    environment:
      DATA_DIR: /data/playbooks
    volumes:
      - ../../data/playbooks:/data/playbooks
