version: '3'

services:
  deeppavlov_ner_rus_bert:
    image: deeppavlov/base-cpu
    environment:
      CONFIG: ner_rus_bert
    volumes:
      - ../../logs:/logs
      - ../../data/deeppavlov/.deeppavlov:/root/.deeppavlov
      - ../../data/deeppavlov/venv:/venv
    ports:
      - 5005:5000

  deeppavlov_ner_ontonotes:
    image: deeppavlov/base-cpu
    environment:
      CONFIG: ner_ontonotes
    volumes:
      - ../../logs:/logs
      - ../../data/deeppavlov/.deeppavlov:/root/.deeppavlov
      - ../../data/deeppavlov/venv:/venv
    ports:
      - 5006:5000
