version: '3'

services:
  engine:
    image: citylix-greenatom-ml/engine:develop
    build: ../images/engine
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/engine:/usr/src/app
    links:
      - clickhouse:clickhouse
    depends_on:
      - kafka

  fetcher.ping:
    image: citylix-greenatom-ml/fetcher.ping:develop
    build: ../images/fetchers/fetcher.ping
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.ping:/usr/src/app
    depends_on:
      - kafka

  fetcher.lync:
    image: citylix-greenatom-ml/fetcher.lync:develop
    build: ../images/fetchers/fetcher.lync
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.lync:/usr/src/app
    depends_on:
      - kafka

  fetcher.active_directory:
    image: citylix-greenatom-ml/fetcher.active_directory:develop
    build: ../images/fetchers/fetcher.active_directory
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.active_directory:/usr/src/app
    depends_on:
      - kafka

  fetcher.vk:
    image: citylix-greenatom-ml/fetcher.vk:develop
    build: ../images/fetchers/fetcher.vk
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.vk:/usr/src/app
      - ../../data/screenshots:/data/screenshots
    depends_on:
      - kafka

  fetcher.ok:
    image: citylix-greenatom-ml/fetcher.ok:develop
    build: ../images/fetchers/fetcher.ok
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.ok:/usr/src/app
      - ../../data/screenshots:/data/screenshots
    depends_on:
      - kafka

  fetcher.fb:
    image: citylix-greenatom-ml/fetcher.fb:develop
    build: ../images/fetchers/fetcher.fb
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.fb:/usr/src/app
      - ../../data/screenshots:/data/screenshots
    depends_on:
      - kafka

  fetcher.instagram:
    image: citylix-greenatom-ml/fetcher.instagram:develop
    build: ../images/fetchers/fetcher.instagram
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetchers/fetcher.instagram:/usr/src/app
      - ../../data/screenshots:/data/screenshots
    depends_on:
      - kafka

  smtp:
    image: citylix-greenatom-ml/smtp:develop
    build: ../images/smtp
    volumes:
      - ../images/smtp:/usr/src/app

  www:
    image: citylix-greenatom-ml/www:develop
    build: ../images/www
    environment:
      DATA_DIR: /data/playbooks/demo
      IMAGE_DIR: /data/images
    volumes:
      - ../images/www:/usr/src/app
      - ../../data/playbooks:/data/playbooks
      - ../../data/images:/data/images
    ports:
      - 80:8501

  simulator:
    image: citylix-greenatom-ml/simulator:develop
    build: ../images/simulator
    volumes:
      - ../images/simulator:/usr/src/app
