version: '3'

services:
  engine:
    image: citylix-greenatom-ml/engine:develop
    build: ../images/engine
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/engine:/usr/src/app
    links:
      - clickhouse:clickhouse
    depends_on:
      - kafka

  fetcher.ping:
    image: citylix-greenatom-ml/fetcher.ping:develop
    build: ../images/fetcher.ping
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetcher.ping:/usr/src/app
    depends_on:
      - kafka

  fetcher.lync:
    image: citylix-greenatom-ml/fetcher.lync:develop
    build: ../images/fetcher.lync
    environment:
      BROKER_URL: "kafka://kafka:9092"
    volumes:
      - ../images/fetcher.lync:/usr/src/app
    depends_on:
      - kafka

  www:
    image: citylix-greenatom-ml/www:develop
    build: ../images/www
    volumes:
      - ../images/www:/usr/src/app
      - ../../data/excel:/data
    ports:
      - 80:8501

  simulator:
    image: citylix-greenatom-ml/simulator:develop
    build: ../images/simulator
    volumes:
      - ../images/simulator:/usr/src/app
