version: '3'

services:
  engine:
    image: citylix-greenatom-ml/engine:develop
    build: ../images/engine
    volumes:
      - ../images/engine:/usr/src/app
    depends_on:
      - kafka

  fetcher.ping:
    image: citylix-greenatom-ml/fetcher.ping:develop
    build: ../images/fetcher.ping
    volumes:
      - ../images/fetcher.ping:/usr/src/app
    depends_on:
      - kafka

  www:
    image: citylix-greenatom-ml/www:develop
    build: ../images/www
    volumes:
     - ../images/www:/usr/src/app
    ports:
      - 80:8501

  simulator:
    image: citylix-greenatom-ml/simulator:develop
    build: ../images/simulator
    volumes:
      - ../images/simulator:/usr/src/app
