version: '3'

services:
  excel:
    image: citylix-greenatom-ml/excel:develop
    build: ../images/excel
    environment:
      DATA_DIR: /data/playbooks/demo
    volumes:
      - ../../data/playbooks:/data/playbooks
