---

  - name: Настройка рабочего окружения Visual Studio Code
    hosts: localhost
    gather_facts: no
    roles:
      - role: mondrik.vscode-workspace
        workspace_name: greenatom-ml-2019-11
        workspace_directory: "{{ current_directory }}"
        git:
          ignoreLimitWarning: !!str true
        python:
          version: 3.7.4
          origin: /opt/anaconda/anaconda-python-3.7
          linting:
            flake8:
              - "--max-line-length=120"
          formatting:
            yapf:
              style: chromium
              indent_width: 4

      - role: mondrik.vscode-workspace-terminal
        uid: app
        title: Приложение
        description: Терминал для разработки приложения
        cwd: "{{ current_directory }}/source"
        anaconda:
          origin: /opt/anaconda/anaconda-python-3.7
          python:
            version: 3.7.4
            packages:
              conda:
                channels:
                  - conda-forge
                dependencies:
                  - invoke

      - role: mondrik.vscode-workspace-terminal
        uid: notebooks
        title: Jupyter notebooks
        description: Терминал для запуска ноутбуков Jupyter
        cwd: "{{ current_directory }}/notebooks"
        history:
          - jupyter notebook
        anaconda:
          origin: /opt/anaconda/anaconda-python-3.7
          python:
            version: 3.7.4
            packages:
              conda:
                channels:
                  - conda-forge
                dependencies:
                  - jupyter
              pip:
                - mimesis
                - Faker
