---

  - name: Настройка рабочего окружения Visual Studio Code
    hosts: localhost
    gather_facts: no
    roles:
      - role: mondrik.vscode-workspace
        workspace_name: greenatom-ml-2019-11
        workspace_directory: "{{ current_directory }}"
        git:
          ignoreLimitWarning: !!str true
        python:
          version: 3.7.4
          origin: /opt/anaconda/anaconda-python-3.7
          linting:
            flake8:
              - "--max-line-length=120"
          formatting:
            yapf:
              style: chromium
              indent_width: 4

      - role: mondrik.vscode-workspace-terminal
        uid: app
        title: Приложение
        description: Терминал для разработки приложения
        cwd: "{{ current_directory }}/source"
        history:
          - docker-compose --file ./docker-compose/kafka.yml up -d kafka
        anaconda:
          origin: /opt/anaconda/anaconda-python-3.7
          python:
            version: 3.7.4
            packages:
              conda:
                channels:
                  - conda-forge
                dependencies:
                  - invoke

      - role: mondrik.vscode-workspace-terminal
        uid: notebooks
        title: Jupyter notebooks
        description: Терминал для запуска ноутбуков Jupyter
        cwd: "{{ current_directory }}/notebooks"
        history:
          - jupyter notebook
        anaconda:
          origin: /opt/anaconda/anaconda-python-3.7
          python:
            version: 3.7.4
            packages:
              conda:
                channels:
                  - conda-forge
                dependencies:
                  - jupyter
                  - requests
              pip:
                - mimesis
                - Faker

      - role: mondrik.vscode-workspace-terminals-group
        uid: deeppavlov
        python:
          version: 3.7.4
          origin: /opt/anaconda/anaconda-python-3.7
          packages:
            conda:
              channels:
                - conda-forge
              dependencies:
                - tensorflow==1.14.0
            pip:
              - email-validator
              - deeppavlov
        terminals:
          - uid: deeppavlov_ner_rus_bert
            title: DeepPavlov - распознавание сущностей
            description: Терминал для распознавания сущностей с DeepPavlov
            cwd: "{{ current_directory }}"
            history:
              - python -m deeppavlov install ner_rus_bert
              - python -m deeppavlov download ner_rus_bert
              - python -m deeppavlov riseapi ner_rus_bert --port 5005
          - uid: deeppavlov_ner_ontonotes
            title: DeepPavlov - распознавание сущностей
            description: Терминал для распознавания сущностей текста с DeepPavlov
            cwd: "{{ current_directory }}"
            history:
              - python -m deeppavlov install ner_ontonotes
              - python -m deeppavlov download ner_ontonotes
              - python -m deeppavlov riseapi ner_ontonotes --port 5006
          - uid: deeppavlov_rusentiment_elmo_twitter_cnn
            title: DeepPavlov - распознавание тональности
            description: Терминал для распознавания тональности текста с DeepPavlov
            cwd: "{{ current_directory }}"
            history:
              - python -m deeppavlov install rusentiment_elmo_twitter_cnn
              - python -m deeppavlov download rusentiment_elmo_twitter_cnn
              - python -m deeppavlov riseapi rusentiment_elmo_twitter_cnn --port 5007
